// Generated by CoffeeScript 1.8.0
Template.team.helpers({
  editing: function() {
    return Session.get('editing') === this._id;
  }
});

Template.team.events({
  "click .edit": function(e, tpl) {
    e.preventDefault();
    return Session.set('editing', this._id);
  },
  "submit form.form-edit": function(e, tpl) {
    var teamName;
    e.preventDefault();
    teamName = tpl.$("input[name='name']").val();
    if (teamName.length) {
      Teams.update(this._id, {
        $set: {
          name: teamName
        }
      });
      return Session.set('editing', null);
    }
  },
  "click .cancel": function(e, tpl) {
    e.preventDefault();
    return Session.set('editing', null);
  },
  "click .remove": function(e, tpl) {
    e.preventDefault();
    return Teams.remove(this._id);
  }
});
